# Accessing Data within Pandas - Lab

## Introduction

In this lab, we'll look at a dataset which contains information on World Cup matches. Let's use the Pandas commands learned in the previous lesson to learn more about our data!

## Objectives
You will be able to: 
- Use pandas methods and attributes to access information about a dataset 
- Index pandas dataframes with .loc, .iloc, and column names 
- Use a boolean mask to index pandas series and dataframes

## Load the data

Load the file `'WorldCupMatches.csv'` as a DataFrame in Pandas.

In [97]:
# Import pandas using the standard alias
import pandas as pd

# Import 'WorldCupMatches.csv' as a DataFrame
file = pd.read_csv('WorldCupMatches.csv')
df = pd.DataFrame(file)
df

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444.0,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346.0,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
847,2014,05 Jul 2014 - 17:00,Quarter-finals,Arena Fonte Nova,Salvador,Netherlands,0,0,Costa Rica,Netherlands win on penalties (4 - 3),51179.0,0,0,Ravshan IRMATOV (UZB),RASULOV Abduxamidullo (UZB),KOCHKAROV Bakhadyr (KGZ),255953,300186488,NED,CRC
848,2014,08 Jul 2014 - 17:00,Semi-finals,Estadio Mineirao,Belo Horizonte,Brazil,1,7,Germany,,58141.0,0,5,RODRIGUEZ Marco (MEX),TORRENTERA Marvin (MEX),QUINTERO Marcos (MEX),255955,300186474,BRA,GER
849,2014,09 Jul 2014 - 17:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0,0,Argentina,Argentina win on penalties (2 - 4),63267.0,0,0,C�neyt �AKIR (TUR),DURAN Bahattin (TUR),ONGUN Tarik (TUR),255955,300186490,NED,ARG
850,2014,12 Jul 2014 - 17:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0,3,Netherlands,,68034.0,0,2,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957,300186502,BRA,NED
851,2014,13 Jul 2014 - 16:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1,0,Argentina,Germany win after extra time,74738.0,0,0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959,300186501,GER,ARG

## Common methods and attributes

Use the correct method to look at the first 7 rows of the dataset.

In [6]:
# Print the first 7 rows of df
df.head(7)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444.0,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346.0,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA
5,1930,16 Jul 1930 - 14:45,Group 1,Parque Central,Montevideo,Chile,3,0,Mexico,,9249.0,1,0,CRISTOPHE Henry (BEL),APHESTEGUY Martin (URU),LANGENUS Jean (BEL),201,1095,CHI,MEX
6,1930,17 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,4,0,Bolivia,,18306.0,0,0,MATEUCCI Francisco (URU),LOMBARDI Domingo (URU),WARNKEN Alberto (CHI),201,1092,YUG,BOL

Look at the last 3 rows of the data set.

In [9]:
# Print the last 3 rows of df
df.tail(3)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
849,2014,09 Jul 2014 - 17:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0,0,Argentina,Argentina win on penalties (2 - 4),63267.0,0,0,C�neyt �AKIR (TUR),DURAN Bahattin (TUR),ONGUN Tarik (TUR),255955,300186490,NED,ARG
850,2014,12 Jul 2014 - 17:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0,3,Netherlands,,68034.0,0,2,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957,300186502,BRA,NED
851,2014,13 Jul 2014 - 16:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1,0,Argentina,Germany win after extra time,74738.0,0,0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959,300186501,GER,ARG

Get a concise summary of the data using `.info()`.

In [10]:
# Print a concise summary of df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 852 entries, 0 to 851
Data columns (total 20 columns):
Year                    852 non-null int64
Datetime                852 non-null object
Stage                   852 non-null object
Stadium                 852 non-null object
City                    852 non-null object
Home Team Name          852 non-null object
Home Team Goals         852 non-null int64
Away Team Goals         852 non-null int64
Away Team Name          852 non-null object
Win conditions          852 non-null object
Attendance              850 non-null float64
Half-time Home Goals    852 non-null int64
Half-time Away Goals    852 non-null int64
Referee                 852 non-null object
Assistant 1             852 non-null object
Assistant 2             852 non-null object
RoundID                 852 non-null int64
MatchID                 852 non-null int64
Home Team Initials      852 non-null object
Away Team Initials      852 non-null object
dtypes: float64(1), int64(7), object(12)
memory usage: 133.2+ KB

Obtain a tuple representing the number of rows and number of columns

In [11]:
# Print the number of rows and columns in df
df.shape

(852, 20)

Use the appropriate attribute to get the column names

In [15]:
# Print the column names of df
col_name = pd.DataFrame(df.columns)
col_name

                       0
0                   Year
1               Datetime
2                  Stage
3                Stadium
4                   City
5         Home Team Name
6        Home Team Goals
7        Away Team Goals
8         Away Team Name
9         Win conditions
10            Attendance
11  Half-time Home Goals
12  Half-time Away Goals
13               Referee
14           Assistant 1
15           Assistant 2
16               RoundID
17               MatchID
18    Home Team Initials
19    Away Team Initials

## Selecting DataFrame information

When looking at the DataFrame's `.head()`, you might have noticed that the games are structured chronologically in the DataFrame.

Use the right selection method to print all the information from the 3rd to the 5th game.

In [23]:
# Print rows 3 through 5
df.iloc[2:6]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA
5,1930,16 Jul 1930 - 14:45,Group 1,Parque Central,Montevideo,Chile,3,0,Mexico,,9249.0,1,0,CRISTOPHE Henry (BEL),APHESTEGUY Martin (URU),LANGENUS Jean (BEL),201,1095,CHI,MEX

Now, print all the info from game 5-9, but we're only interested in printing out the, "Home Team Name" and the, "Away Team Name."

In [32]:
# Print rows 5 through 9 and columns 'Home Team Name' and 'Away Team Name'
df.loc[5:9, ['Home Team Name','Away Team Name']]

  Home Team Name Away Team Name
5          Chile         Mexico
6     Yugoslavia        Bolivia
7            USA       Paraguay
8        Uruguay           Peru
9          Chile         France

Next, we'd like the information on all the games played in Group 3 for the 1950 World Cup.

In [63]:
# Print all info for games played in 1950 for Group 3
group3 = df.loc[(df['Stage'] == 'Group 2')]
group3

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
6,1930,17 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,4,0,Bolivia,,18306.0,0,0,MATEUCCI Francisco (URU),LOMBARDI Domingo (URU),WARNKEN Alberto (CHI),201,1092,YUG,BOL
11,1930,20 Jul 1930 - 13:00,Group 2,Estadio Centenario,Montevideo,Brazil,4,0,Bolivia,,25466.0,1,0,BALWAY Thomas (FRA),MATEUCCI Francisco (URU),VALLEJO Gaspar (MEX),201,1091,BRA,BOL
54,1950,25 Jun 1950 - 15:00,Group 2,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,England,2,0,Chile,,29703.0,1,0,VAN DER MEER Karel (NED),GARDELLI Mario (BRA),DAHLNER Gunnar (SWE),208,1192,ENG,CHI
55,1950,25 Jun 1950 - 15:00,Group 2,Durival de Brito,Curitiba,Spain,3,1,USA,,9511.0,0,1,VIANA Mario (BRA),DA COSTA VIEIRA Jose (POR),DE LA SALLE Charles (FRA),208,1208,ESP,USA
60,1950,29 Jun 1950 - 15:00,Group 2,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Spain,2,0,Chile,,19790.0,2,0,MALCHER Alberto (BRA),MARINO Esteban (URU),ALVAREZ Alfredo (BOL),208,1193,ESP,CHI
62,1950,29 Jun 1950 - 15:00,Group 2,Independencia,Belo Horizonte,USA,1,0,England,,10151.0,1,0,DATTILO Generoso (ITA),DE LA SALLE Charles (FRA),GALEATI Giovanni (ITA),208,1202,USA,ENG
64,1950,02 Jul 1950 - 15:00,Group 2,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Spain,1,0,England,,74462.0,0,0,GALEATI Giovanni (ITA),LUTZ Jean (SUI),DATTILO Generoso (ITA),208,1199,ESP,ENG
68,1950,02 Jul 1950 - 15:00,Group 2,Ilha do Retiro,Recife,Chile,5,2,USA,,8501.0,2,0,GARDELLI Mario (BRA),HEYEN Mario Ruben (PAR),ALVAREZ Alfredo (BOL),208,1194,CHI,USA
79,1954,17 Jun 1954 - 18:00,Group 2,Wankdorf Stadium,Berne,Germany FR,4,1,Turkey,,28000.0,1,1,DA COSTA VIEIRA Jose (POR),ZSOLT Istvan (HUN),MERLOTTI Armand (SUI),211,1283,FRG,TUR
80,1954,17 Jun 1954 - 18:00,Group 2,Hardturm,Zurich,Hungary,9,0,Korea Republic,,13000.0,4,0,VINCENTI Raymond (FRA),VON GUNTER Albert (SUI),STEINER Carl (AUT),211,1294,HUN,KOR
87,1954,20 Jun 1954 - 16:50,Group 2,St. Jakob,Basel,Hungary,8,3,Germany FR,,56000.0,3,1,LING William (ENG),SCHICKER Werner (SUI),GRIFFITHS Benjamin (WAL),211,1277,HUN,FRG
88,1954,20 Jun 1954 - 17:00,Group 2,Charmilles,Geneva,Turkey,7,0,Korea Republic,,4000.0,4,0,MARINO Esteban (URU),ORLANDINI Vincenzo (ITA),SCHONHOLZER Ernest (SUI),211,1304,TUR,KOR
91,1954,23 Jun 1954 - 18:00,Group 2,Hardturm,Zurich,Germany FR,7,2,Turkey,,17000.0,3,1,VINCENTI Raymond (FRA),FAULTLESS Charlie (SCO),DOERFLINGER Ernst (SUI),211,1284,FRG,TUR
105,1958,08 Jun 1958 - 19:00,Group 2,Idrottsparken,Norrk�Ping,France,7,3,Paraguay,,16518.0,2,2,GARDEAZABAL Juan (ESP),GRIFFITHS Benjamin (WAL),BROZZI Juan (ARG),220,1386,FRA,PAR
106,1958,08 Jun 1958 - 19:00,Group 2,Arosvallen,Vasteras,Yugoslavia,1,1,Scotland,,9591.0,1,0,WYSSLING Paul (SUI),ORLANDINI Vincenzo (ITA),MACKO Martin (TCH),220,1434,YUG,SCO
111,1958,11 Jun 1958 - 19:00,Group 2,Idrottsparken,Norrk�Ping,Paraguay,3,2,Scotland,,11665.0,2,1,ORLANDINI Vincenzo (ITA),GARDEAZABAL Juan (ESP),ANDREN Bengt (SWE),220,1423,PAR,SCO
112,1958,11 Jun 1958 - 19:00,Group 2,Arosvallen,Vasteras,Yugoslavia,3,2,France,,12217.0,1,1,GRIFFITHS Benjamin (WAL),WYSSLING Paul (SUI),DRAGVOLL Georg (NOR),220,1388,YUG,FRA
121,1958,15 Jun 1958 - 19:00,Group 2,Tunavallen,Eskilstuna,Paraguay,3,3,Yugoslavia,,13103.0,1,2,MACKO Martin (TCH),GRIFFITHS Benjamin (WAL),GARDEAZABAL Juan (ESP),220,1426,PAR,YUG
122,1958,15 Jun 1958 - 19:00,Group 2,Eyravallen,Orebro,France,2,1,Scotland,,13554.0,2,0,BROZZI Juan (ARG),ORLANDINI Vincenzo (ITA),WYSSLING Paul (SUI),220,1387,FRA,SCO
139,1962,30 May 1962 - 15:00,Group 2,Nacional,Santiago De Chile,Chile,3,1,Switzerland,,65006.0,1,1,ASTON Ken (ENG),BLAVIER Arthur (BEL),YAMASAKI MALDONADO Arturo (MEX),231,1473,CHI,SUI
143,1962,31 May 1962 - 15:00,Group 2,Nacional,Santiago De Chile,Germany FR,0,0,Italy,,65440.0,0,0,DAVIDSON Bob (SCO),MORGAN Raymond (CAN),VENTRE Luis Antonio (ARG),231,1507,FRG,ITA
147,1962,02 Jun 1962 - 15:00,Group 2,Nacional,Santiago De Chile,Chile,2,0,Italy,,66057.0,0,0,ASTON Ken (ENG),GOLDSTEIN Leo (USA),BUERGO Fernando (MEX),231,1472,CHI,ITA
151,1962,03 Jun 1962 - 15:00,Group 2,Nacional,Santiago De Chile,Germany FR,2,1,Switzerland,,64922.0,1,0,HORN Leo (NED),LATYCHEV Nikolaj (URS),VENTRE Luis Antonio (ARG),231,1510,FRG,SUI
155,1962,06 Jun 1962 - 15:00,Group 2,Nacional,Santiago De Chile,Germany FR,2,0,Chile,,67224.0,1,0,DAVIDSON Bob (SCO),ASTON Ken (ENG),HORN Leo (NED),231,1471,FRG,CHI
159,1962,07 Jun 1962 - 15:00,Group 2,Nacional,Santiago De Chile,Italy,3,0,Switzerland,,59828.0,1,0,LATYCHEV Nikolaj (URS),DAVIDSON Bob (SCO),RUMENTCHEV Dimitar (BUL),231,1532,ITA,SUI
169,1966,12 Jul 1966 - 19:30,Group 2,Hillsborough,Sheffield,Germany FR,5,0,Switzerland,,36127.0,3,0,PHILLIPS Hugh (SCO),ADAIR John (NIR),LOEOEW Bertil (SWE),238,1656,FRG,SUI
174,1966,13 Jul 1966 - 19:30,Group 2,Villa Park,Birmingham,Argentina,2,1,Spain,,42738.0,0,0,RUMENTCHEV Dimitar (BUL),YAMASAKI MALDONADO Arturo (MEX),ZECEVIC Konstantin (YUG),238,1578,ARG,ESP
177,1966,15 Jul 1966 - 19:30,Group 2,Hillsborough,Sheffield,Spain,2,1,Switzerland,,32028.0,0,1,BAKHRAMOV Tofik (URS),ZSOLT Istvan (HUN),PHILLIPS Hugh (SCO),238,1641,ESP,SUI
181,1966,16 Jul 1966 - 15:00,Group 2,Villa Park,Birmingham,Germany FR,0,0,Argentina,,46587.0,0,0,ZECEVIC Konstantin (YUG),FERNANDES CAMPOS Joaquim (POR),LOEOEW Bertil (SWE),238,1579,FRG,ARG
185,1966,19 Jul 1966 - 19:30,Group 2,Hillsborough,Sheffield,Argentina,2,0,Switzerland,,32127.0,0,0,FERNANDES CAMPOS Joaquim (POR),ZSOLT Istvan (HUN),BAKHRAMOV Tofik (URS),238,1582,ARG,SUI
190,1966,20 Jul 1966 - 19:30,Group 2,Villa Park,Birmingham,Germany FR,2,1,Spain,,42187.0,1,1,MARQUES Armando (BRA),VICUNA Claudio (CHI),CHOI Duk Ryong (PRK),238,1637,FRG,ESP
201,1970,02 Jun 1970 - 16:00,Group 2,Cuauhtemoc,Puebla,Uruguay,2,0,Israel,,20654.0,1,0,DAVIDSON Bob (SCO),SCHEURER Ruedi (SUI),TAREKEGN Seyoum (ETH),250,1881,URU,ISR
204,1970,03 Jun 1970 - 16:00,Group 2,Luis Dosal,Toluca,Italy,1,0,Sweden,,13433.0,1,0,TAYLOR John (ENG),SCHEURER Ruedi (SUI),KANDIL Aly Hussein (EGY),250,1883,ITA,SWE
208,1970,06 Jun 1970 - 16:00,Group 2,Cuauhtemoc,Puebla,Uruguay,0,0,Italy,,29968.0,0,0,GLOECKNER Rudolf (GDR),TSCHENSCHER Kurt (GER),HORVAT Drago (YUG),250,1884,URU,ITA
212,1970,07 Jun 1970 - 12:00,Group 2,Luis Dosal,Toluca,Sweden,1,1,Israel,,9624.0,0,0,TAREKEGN Seyoum (ETH),RADULESCU Andrei (ROU),HORVAT Drago (YUG),250,1880,SWE,ISR
216,1970,10 Jun 1970 - 16:00,Group 2,Cuauhtemoc,Puebla,Sweden,1,0,Uruguay,,18163.0,0,0,LANDAUER Henry (USA),TAYLOR John (ENG),RADULESCU Andrei (ROU),250,1922,SWE,URU
220,1970,11 Jun 1970 - 16:00,Group 2,Luis Dosal,Toluca,Italy,0,0,Israel,,9890.0,0,0,DE MORAES Ayrton Vieira (BRA),TAREKEGN Seyoum (ETH),TSCHENSCHER Kurt (GER),250,1877,ITA,ISR
232,1974,13 Jun 1974 - 17:00,Group 2,Waldstadion,Frankfurt/Main,Brazil,0,0,Yugoslavia,,62000.0,0,0,SCHEURER Ruedi (SUI),LORAUX Vital (BEL),PESTARINO Luis (ARG),262,1986,BRA,YUG
235,1974,14 Jun 1974 - 19:30,Group 2,Westfalenstadion,Dortmund,Zaire,0,2,Scotland,,27000.0,0,2,SCHULENBURG Gerhard (GER),BOSKOVIC Tony (AUS),WEYLAND Hans Joachim (FRG),262,2176,ZAI,SCO
241,1974,18 Jun 1974 - 19:30,Group 2,Waldstadion,Frankfurt/Main,Scotland,0,0,Brazil,,62000.0,0,0,VAN GEMERT Arie (NED),PALOTAI Karoly (HUN),LINEMAYR Erich (AUT),262,1985,SCO,BRA
243,1974,18 Jun 1974 - 19:30,Group 2,Parkstadion,Gelsenkirchen,Yugoslavia,9,0,Zaire,,31700.0,6,0,DELGADO Omar (COL),LLOBREGAT Vicente (VEN),BARRETO RUIZ Ramon (URU),262,2186,YUG,ZAI
248,1974,22 Jun 1974 - 16:00,Group 2,Waldstadion,Frankfurt/Main,Scotland,1,1,Yugoslavia,,56000.0,0,0,GONZALEZ ARCHUNDIA Alfonso (MEX),GLOECKNER Rudolf (GDR),TSCHENSCHER Kurt (GER),262,2175,SCO,YUG
250,1974,22 Jun 1974 - 16:00,Group 2,Parkstadion,Gelsenkirchen,Zaire,0,3,Brazil,,36200.0,0,1,RAINEA Nicolae (ROU),ANGONESE Aurelio (ITA),OHMSEN Klaus (GER),262,1987,ZAI,BRA
270,1978,01 Jun 1978 - 15:00,Group 2,El Monumental - Estadio Monumental Antonio Ves...,Buenos Aires,Germany FR,0,0,Poland,,67579.0,0,0,COEREZZA Norberto Angel (ARG),ITHURRALDE Arturo Andres (ARG),COMESANA Miguel (ARG),278,2351,FRG,POL
272,1978,02 Jun 1978 - 16:45,Group 2,Arroyito - Estadio Dr. Lisandro de la Torre,Rosario,Tunisia,3,1,Mexico,,17396.0,0,1,GORDON John (SCO),DUBACH Jean (SUI),GONELLA Sergio (ITA),278,2433,TUN,MEX
279,1978,06 Jun 1978 - 16:45,Group 2,Arroyito - Estadio Dr. Lisandro de la Torre,Rosario,Poland,1,0,Tunisia,,9624.0,1,0,MARTINEZ Angel (ESP),PESTARINO Luis (ARG),THOMAS Clive (WAL),278,2454,POL,TUN
280,1978,06 Jun 1978 - 16:45,Group 2,Estadio Ol�mpico Chateau Carreras,Cordoba,Germany FR,6,0,Mexico,,35258.0,4,0,BOUZO Farouk (SYR),GARRIDO Antonio (POR),RION Francis (BEL),278,2350,FRG,MEX
287,1978,10 Jun 1978 - 16:45,Group 2,Arroyito - Estadio Dr. Lisandro de la Torre,Rosario,Poland,3,1,Mexico,,22651.0,1,0,NAMDAR Jafar (IRN),ERIKSSON Ulf (SWE),CORVER Charles (NED),278,2431,POL,MEX
288,1978,10 Jun 1978 - 16:45,Group 2,Estadio Ol�mpico Chateau Carreras,Cordoba,Germany FR,0,0,Tunisia,,30667.0,0,0,OROZCO GUERRERO Cesar (PER),COMESANA Miguel (ARG),PESTARINO Luis (ARG),278,2352,FRG,TUN
314,1982,16 Jun 1982 - 17:15,Group 2,El Molinon,Gijon,Germany FR,1,2,Algeria,,42000.0,0,0,LABO REVOREDO Enrique (PER),ARISTIZABAL MURCIA Gilberto (COL),CASARIN Paolo (ITA),293,741,FRG,ALG
317,1982,17 Jun 1982 - 17:15,Group 2,Carlos Tartiere,Oviedo,Chile,0,1,Austria,,22500.0,0,1,CARDELLINO DE SAN VICENTE Juan (URU),CASARIN Paolo (ITA),ARISTIZABAL MURCIA Gilberto (COL),293,764,CHI,AUT
326,1982,20 Jun 1982 - 17:15,Group 2,El Molinon,Gijon,Germany FR,4,1,Chile,,42000.0,1,0,GALLER Bruno (SUI),CHRISTOV Vojtech (TCH),BOSKOVIC Tony (AUS),293,813,FRG,CHI
329,1982,21 Jun 1982 - 17:15,Group 2,Carlos Tartiere,Oviedo,Algeria,0,2,Austria,,22000.0,0,0,BOSKOVIC Tony (AUS),CHRISTOV Vojtech (TCH),AL DOY Ebrahim (BHR),293,739,ALG,AUT
338,1982,24 Jun 1982 - 17:15,Group 2,Carlos Tartiere,Oviedo,Algeria,3,2,Chile,,16000.0,3,0,MENDEZ MOLINA Romulo (GUA),FREDRIKSSON Erik (SWE),COELHO Arnaldo (BRA),293,740,ALG,CHI
341,1982,25 Jun 1982 - 17:15,Group 2,El Molinon,Gijon,Germany FR,1,0,Austria,,41000.0,1,0,VALENTINE Robert (SCO),AL DOY Ebrahim (BHR),COELHO Arnaldo (BRA),293,770,FRG,AUT
347,1982,29 Jun 1982 - 21:00,Group 2,Santiago Bernabeu,Madrid,Germany FR,0,0,England,,75000.0,0,0,COELHO Arnaldo (BRA),ORTIZ Hector (PAR),MENDEZ MOLINA Romulo (GUA),294,879,FRG,ENG
351,1982,02 Jul 1982 - 21:00,Group 2,Santiago Bernabeu,Madrid,Germany FR,2,1,Spain,,90089.0,0,0,CASARIN Paolo (ITA),WOEHRER Franz (AUT),PALOTAI Karoly (HUN),294,900,FRG,ESP
355,1982,05 Jul 1982 - 21:00,Group 2,Santiago Bernabeu,Madrid,Spain,0,0,England,,75000.0,0,0,PONNET Alexis (BEL),VAUTROT Michel (FRA),LACARNE Belaid (ALG),294,877,ESP,ENG

Let's repeat the command above, but now we only want to print out the attendance column for the Group 3 games.

You can combine conditions like this:

`df[(condition1) | (condition2)]`  -> Returns rows where either condition is true

`df[(condition1) & (condition2)]`  -> Returns rows where both conditions are true

In [48]:
# Print the 'Attendance' column for games played in 1950 for Group 3
attendance = df.loc[(df['Stage'] == 'Group 3') & (df['Year'] == 1950), ['Attendance', 'Home Team Goals']]
print(type(attendance))
attendance

<class 'pandas.core.frame.DataFrame'>

    Attendance  Home Team Goals
56     36502.0                3
61      7903.0                2
65     25811.0                2

Throughout the entire history of the World Cup, how many home games were played by the Netherlands?

In [53]:
# Number of home games played by the Netherlands
netherlands_homegame = df.loc[(df['Home Team Name'] == 'Netherlands')]
no_of_homegames_played = len(netherlands_homegame)
no_of_homegames_played

32

How many games were played by the Netherlands in total?

In [58]:
# Number of games played by the Netherlands in total
netherlands_games = df.loc[(df['Home Team Name'] == 'Netherlands') | (df['Away Team Name'] == 'Netherlands')]
no_of_games_played = len(netherlands_games)
no_of_games_played

54

Next, let's try and figure out how many games the USA played in the 2014 World Cup.

In [75]:
# Number of games the USA played in the 2014 world cup
usa_games = df.loc[((df['Home Team Name'] == 'USA') | (df['Away Team Name'] == 'USA')) & (df['Year'] == 2014)]
no_of_games_played = len(usa_games)
no_of_games_played
# usa_games_2014

5

Now, let's try to find out how many countries participated in the 1986 World Cup.

Hint 1: as a first step, create a new dataset that only contains games in that year.

Hint 2: You can use `.unique()` to make sure you don't end up with duplicate country names.

In [96]:
# Number of countries participated in the 1986 world cup
game_1986 = df.loc[(df['Year'] == 1986)]
home = game_1986.loc[:,'Home Team Name']
away = game_1986.loc[:,'Away Team Name']
appened_array = pd.concat([home, away])
teams_1986 = appened_array.unique()
number_of_teams_1986 = len(teams_1986)
number_of_teams_1986

24

In World Cup history, how matches had more than 5 goals in total?

In [110]:
# Number of matches that had more than 5 goals in total
matches_over_5goals = df.loc[(df['Stage'] == 'Final')]
len(matches_over_5goals.loc[(matches_over_5goals['Home Team Goals'] + matches_over_5goals['Away Team Goals']) > 5])

4

## Changing values and creating new columns

With the information you currently have in your `df`, create a new column, "Half-time Goals."

In [118]:
# Create a new column 'Half-time Goals' in df
df['Half-time Goals']

0      0
1      0
2      0
3      0
4      0
      ..
847    0
848    0
849    0
850    0
851    0
Name: Half-time Goals, Length: 852, dtype: int64

Run the code below. You'll notice that for Korea, there are records for both North-Korea (Korea DPR) and South-Korea (Korea Republic).

In [119]:
# Print all records containing the string 'Korea'
df.loc[df['Home Team Name'].str.contains('Korea'), 'Home Team Name']

179         Korea DPR
187         Korea DPR
374    Korea Republic
386    Korea Republic
434    Korea Republic
444    Korea Republic
480    Korea Republic
524    Korea Republic
593    Korea Republic
609    Korea Republic
635    Korea Republic
642    Korea Republic
655    Korea Republic
710    Korea Republic
753         Korea DPR
802    Korea Republic
818    Korea Republic
Name: Home Team Name, dtype: object

Imagine that, for some reason, we simply want Korea listed as one entry, so we want to replace every "Home Team Name" and "Away Team Name" entry that contains "Korea" to simply "Korea". In the same way, we want to change the columns "Home Team Initials" and "Away Team Initials" to NSK (North & South Korea) instead of "KOR" and "PRK".

In [122]:
# Update the 'Home Team Name' and 'Home Team Initials' columns 
df.loc[(df['Home Team Name'].str.contains('Korea')), 
       ['Home Team Name']] = "Korea"
df.loc[(df['Away Team Name'].str.contains('Korea')), 
       ['Home Team Name', 'Away Team Name']] = "Korea"
df.loc[df['Home Team Name'].str.contains('Korea'), ['Home Team Name', 'Away Team Name']]

    Home Team Name Away Team Name
80           Korea          Korea
88           Korea          Korea
171          Korea          Korea
179          Korea          Chile
187          Korea          Italy
195          Korea          Korea
364          Korea          Korea
374          Korea       Bulgaria
386          Korea          Italy
421          Korea          Korea
434          Korea          Spain
444          Korea        Uruguay
464          Korea          Korea
480          Korea        Bolivia
490          Korea          Korea
524          Korea         Mexico
542          Korea          Korea
556          Korea          Korea
593          Korea         Poland
609          Korea            USA
625          Korea          Korea
635          Korea          Italy
639          Korea          Korea
640          Korea          Korea
642          Korea         Turkey
655          Korea           Togo
672          Korea          Korea
691          Korea          Korea
710          Korea         Greece
721          Korea          Korea
725          Korea          Korea
737          Korea          Korea
742          Korea          Korea
753          Korea  C�te d'Ivoire
756          Korea          Korea
788          Korea          Korea
802          Korea        Algeria
818          Korea        Belgium

Make sure to verify your answer!

In [123]:
# Check the updated columns
df.loc[df['Home Team Name'].str.contains('Korea'), ['Home Team Name', 'Away Team Name']]

    Home Team Name Away Team Name
80           Korea          Korea
88           Korea          Korea
171          Korea          Korea
179          Korea          Chile
187          Korea          Italy
195          Korea          Korea
364          Korea          Korea
374          Korea       Bulgaria
386          Korea          Italy
421          Korea          Korea
434          Korea          Spain
444          Korea        Uruguay
464          Korea          Korea
480          Korea        Bolivia
490          Korea          Korea
524          Korea         Mexico
542          Korea          Korea
556          Korea          Korea
593          Korea         Poland
609          Korea            USA
625          Korea          Korea
635          Korea          Italy
639          Korea          Korea
640          Korea          Korea
642          Korea         Turkey
655          Korea           Togo
672          Korea          Korea
691          Korea          Korea
710          Korea         Greece
721          Korea          Korea
725          Korea          Korea
737          Korea          Korea
742          Korea          Korea
753          Korea  C�te d'Ivoire
756          Korea          Korea
788          Korea          Korea
802          Korea        Algeria
818          Korea        Belgium

## Summary

In this lab, you learned how to access data within Pandas!